Feature/PT-1/main page
dungeon-slave/market_client pull request #1
Opened 2023-06-28 13:38 UTC by dungeon-slave

Create main_menu_screen widget
Create dish_item widget
Create tab_bar widget
End project setup
Add DI
Add all layers
Add all necessary widgets
Implement MainMenu feature

https://github.com/dungeon-slave/food_app/assets/70040363/4af4b4ea-05e8-462f-8b27-32fd017cb8dd

2023-06-30 15:41 UTC, Alexey-Lebedzeu requested changes

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on core/lib/di/data_di.dart
перениси дата ди в дату , не делай лишнюю зависимость в коре

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on core/pubspec.yaml
> +    path: ../domain
и кор по идее не должен зависеть от даты и домена

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/colors.dart
> +class MyColors {
naming

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/dimens.dart
> +  static const double dishesPadding = 10;
сделай что-то вроде `  static const double BORDER_RADIUS_48 = 48.0;
  static const double BORDER_RADIUS_100 = 100.0;

  static const double PADDING_2 = 2.0;
`

тк значения переиспользуются,

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/fonts.dart
> +  static const dishNameFont = TextStyle(
сделай дефолты шрифтов типо `
  static TextStyle bold22 = TextStyle(
    fontFamily: GoogleFonts.roboto().fontFamily,
    fontWeight: FontWeight.w600,
    fontSize: 22,
  );
` тк они опять же могут использоватся много где одинаковыми

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/data.dart
> +library;
просто библиотека?? а где название ?

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +  late final List<DishEntity> dishEntities = [];
очень плохая идея.. хранить инфу прямо в провайдере. делай или стор локальный или храни уже загруженные в блоке, но никак не в репе или провайдере

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +    for (var dish in dishEntities) {
var ?

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +                      .collection('menu')
константы коллекций вынеси в кор в файл констант

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +      dishEntities.add(DishEntity(
напиши методы для энтити fromJson . или используй сериализаторы

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +      dishEntities.add(DishEntity(
лучше конечно второй вариант

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +    return;
что за пустой ретурн

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/providers/firebase_provider.dart
> +    final fbMenu = (await FirebaseFirestore
где тип ?

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on data/lib/repositories/dishes_repository_impl.dart
> +class DishesRepository implements IDishesRepository {
что с нэймингом ?

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on domain/lib/repositories/dishes_repository_interface.dart
> +abstract class IDishesRepository {
что с неймингом ?

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on domain/lib/usecase/fetch_dishes_usecase.dart
> +class FetchDishesUsecase implements IUseCase<String, List<DishModel>> {
IUseCase????

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on domain/lib/usecase/usecase.dart
> +abstract class IUseCase<Input, Output> {
naming

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on domain/pubspec.yaml
> +    path: ../core
зачем?

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/dish_item.dart
> +  const DishItem(this._name, this._imageRef, this._price, {super.key});
if you have more then 1 parameters make they named parameter

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/dish_item.dart
> +          top: Dimens.vertCardMargin, bottom: Dimens.vertCardMargin),
add ,

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/dish_item.dart
> +          top: Dimens.vertCardPadding, bottom: Dimens.vertCardPadding),
,

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/dish_item.dart
> +        children: [
type

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/dish_item.dart
> +          Image.network(
create one image for whole app like AppImage

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/dish_item.dart
> +            children: [
type

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/tab_bar.dart
> +                          .add(ChangeTypeEvent(dishesTypes[value]!));
,

2023-06-30 15:41 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/tab_bar.dart
> +            ..add(ChangeTypeEvent(dishesTypes[0]!)),
,

2023-06-30 16:02 UTC, Alexey-Lebedzeu requested changes

2023-06-30 16:02 UTC, Alexey-Lebedzeu commented on features/main_menu/lib/src/ui/tab_bar.dart
> +  };
move to state

2023-06-30 16:16 UTC, dungeon-slave commented on data/lib/providers/firebase_provider.dart
> +    return;
> что за пустой ретурн

Void же) Просто мне кажется так нагляднее где функция работу заканчивает. Или не надо в void-функциях return писать?

2023-06-30 16:22 UTC, dungeon-slave commented on data/lib/repositories/dishes_repository_impl.dart
> +class DishesRepository implements IDishesRepository {
Ты про IDishesRepository? Объясняю смысл мува: я смотрел тестовый что вы кидали и там интерфейсы называются как обычные классы, а у реализации в конце Impl добавляется. Я подумал, что удобнее и нагляднее будет в интерфейсах спереди добавлять букву I, а остальные классы оставить как есть. Тк так ты сразу понимаешь что перед тобой интерфейс находится, а в случае с Impl мне надо всё название класса до конца дочитать, что трудозатратнее. Ну если так делать нельзя, то я буду писать Impl в конце реализаций

2023-06-30 16:27 UTC, dungeon-slave commented on data/lib/repositories/dishes_repository_impl.dart
> +class DishesRepository implements IDishesRepository {
Просто, мне кажется, это из разряда тех вещей как вы с командой договоритесь. Я вот с собой так говорился. Хорошая практика, в Си Шарпе по дефолту используется, в тайпскрипте встречал

2023-07-13 08:13 UTC, Alexey-Lebedzeu approved these changes

2023-07-13 08:13 UTC, merged