fixes/pt-5/authentication
dungeon-slave/market_client pull request #13
Opened 2023-08-09 09:53 UTC by dungeon-slave

https://github.com/dungeon-slave/food_app/assets/70040363/867946fa-ac14-4ee1-b432-f58dc82e7b3a

migrate to the new auto_route
make responsive app bars
create text_field core widget
end sign-in/sign-out layout
fix navigation
typo fixes

2023-08-09 15:45 UTC, ibondarovich requested changes

2023-08-09 15:45 UTC, ibondarovich commented on core_ui/lib/src/widgets/app_button.dart
> +          backgroundColor: Theme.of(context).indicatorColor),
,

2023-08-09 15:45 UTC, ibondarovich commented on domain/lib/usecase/authentication/save_user_usecase.dart
> +      {required AuthenticationRepository authenticationRepository})
formatting

2023-08-09 15:45 UTC, ibondarovich commented on domain/lib/usecase/text_scale/set_text_scale_usecase.dart
> +  Future<void> execute(double input) async => await _textScaleRepository.saveTextScale(input);
formatting

2023-08-09 15:45 UTC, ibondarovich commented on features/detailed_page/pubspec.yaml
> +  auto_route_generator: ^7.3.0
to dev dependencies

2023-08-09 15:45 UTC, ibondarovich commented on features/main_page_screen/pubspec.yaml
> +  auto_route_generator: ^7.3.0
to dev dependencies

2023-08-09 15:45 UTC, ibondarovich commented on features/sign_up_screen/lib/src/bloc/sign_up_bloc.dart
> +      SignUpEvent event, Emitter<SignUpState> emit) async {
,

2023-08-09 15:45 UTC, ibondarovich commented on features/sign_up_screen/lib/src/bloc/sign_up_bloc.dart
> +    //TODO implement state change
?

2023-08-09 15:45 UTC, ibondarovich commented on navigation/lib/src/app_router/auth_guard.dart
> +          predicate: (Route<dynamic> predicate) => false);
,

2023-08-13 19:26 UTC, dungeon-slave commented on features/sign_up_screen/lib/src/bloc/sign_up_bloc.dart
> +    //TODO implement state change
fix in next PR

2023-08-14 10:34 UTC, merged