feature/PT-6/order-history
dungeon-slave/market_client pull request #14
Opened 2023-08-14 09:07 UTC by dungeon-slave

add order history feature
fixes

2023-08-14 12:46 UTC, ibondarovich requested changes

2023-08-14 12:46 UTC, ibondarovich commented on data/lib/repositories/authentication_repository_impl.dart
> +  bool checkUser() => _hiveProvider.fetchUserId() != '' ? true : false;
naming

2023-08-14 12:46 UTC, ibondarovich commented on features/dishes_menu/lib/src/ui/dish_item.dart
> +            AddDishEvent(model: _model)
,

2023-08-14 12:46 UTC, ibondarovich commented on features/home_screen/lib/src/ui/home_screen.dart
> +                                const AppIcon(AppIconsData.selectedShoppingCart),
,

2023-08-14 12:46 UTC, ibondarovich commented on features/home_screen/lib/src/ui/home_screen.dart
> +                                const AppIcon(AppIconsData.unselectedShoppingCart),
,

2023-08-14 12:46 UTC, ibondarovich commented on features/order_history/lib/src/ui/components/main_info.dart
> +            '${AppConstants.date}: ${_model.dateTime.day}.${_model.dateTime.month}.${_model.dateTime.year}',
formatting?

2023-08-14 12:46 UTC, ibondarovich commented on features/order_history/lib/src/ui/components/main_info.dart
> +            '${AppConstants.time}: ${_model.dateTime.hour}:${_model.dateTime.minute}',
same

2023-08-14 12:46 UTC, ibondarovich commented on features/order_history/lib/src/ui/components/main_info.dart
> +            '${AppConstants.total}: ${_model.price.toStringAsFixed(AppConstants.priceSize)}\$',
same

2023-08-14 12:46 UTC, ibondarovich commented on features/order_history/lib/src/ui/components/order_history_item.dart
> +                                '${index + 1}. ${widget._model.products[index].dishModel.name} x ${widget._model.products[index].count}',
same

2023-08-14 12:46 UTC, ibondarovich commented on features/shopping_cart/lib/src/ui/shopping_cart.dart
>                      builder: (context, state) {
type

2023-08-14 12:46 UTC, ibondarovich commented on features/shopping_cart/lib/src/ui/shopping_cart.dart
>                    builder: (context, state) {
type

2023-08-14 12:46 UTC, ibondarovich commented on features/sign_in_screen/lib/src/ui/sign_in_screen.dart
> +          builder: (context, state) {
type

2023-08-14 12:46 UTC, ibondarovich commented on features/sign_up_screen/lib/src/ui/sign_up_screen.dart
>    final _passwordController = TextEditingController();
type

2023-08-14 12:46 UTC, ibondarovich commented on features/sign_up_screen/lib/src/ui/sign_up_screen.dart
> +          builder: (context, state) {
type

2023-08-17 12:07 UTC, Alexey-Lebedzeu requested changes

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/app_constants.dart
> +  static const emptyList = 'It\'s empty here...';
type

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/app_constants.dart
> +  static const int cartSnackBarDuration = 2;
separate

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on data/lib/providers/remote/firebase_provider.dart
> +  Future<List<DishTypeEntity>> fetchMenu() async =>
refactor this

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on data/lib/repositories/cart_repository_impl.dart
> +    await _networkService.checkConnection()
refactor this to safe request

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on domain/lib/repositories/authentication_repository.dart
>    Future<void> saveUser(String userId);
replace

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on domain/lib/usecase/shopping_cart/send_order_usecase.dart
> +  Future<void> execute(OrderModel input) async =>
remove async

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/detailed_page/lib/src/ui/detailed_page_screen.dart
>                  onPressed: () => context.router.pop(),
to bloc

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/order_history/lib/src/ui/components/order_history_item.dart
> +                  _isVisible
if

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/order_history/lib/src/ui/order_history.dart
> +            builder: (context, state) {
type

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/order_history/lib/src/ui/order_history.dart
> +      create: (context) => OrderHistoryBloc(
type

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/shopping_cart/lib/src/bloc/shopping_cart/shopping_cart_bloc.dart
>      int index = state.items.indexWhere((CartItemModel element) =>
remove it and impl increment and decrement in model

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/shopping_cart/lib/src/bloc/shopping_cart/shopping_cart_bloc.dart
> +          id: DateTime.now().microsecondsSinceEpoch.toString(),
UUID

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/shopping_cart/lib/src/ui/shopping_cart.dart
> +                  width: kTextTabBarHeight * 8,
refactor this

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/sign_in_screen/lib/src/bloc/sign_in_bloc.dart
> +          const SignInState(),
,?

2023-08-17 12:07 UTC, Alexey-Lebedzeu commented on features/sign_up_screen/lib/src/bloc/sign_up_bloc.dart
> +      String userId = await _emailSignUpUseCase.execute(event.data);
final

2023-08-24 13:03 UTC, merged