feature/PT-4/local_storage
dungeon-slave/market_client pull request #9
Opened 2023-07-26 09:54 UTC by dungeon-slave

add pop-up with info about connection
implement menu saving in local storage
add textScale feature
add textScale saving in local storage
add settings item

https://github.com/dungeon-slave/food_app/assets/70040363/08c0fb34-f624-46c3-ad97-1be86314b302

2023-08-09 15:29 UTC, ibondarovich requested changes

2023-08-09 15:29 UTC, ibondarovich commented on core_ui/lib/src/theme/app_constants.dart
> +  static const List<double> textScales = [0.8, 1.0, 1.2];
use enum

2023-08-09 15:29 UTC, ibondarovich commented on data/lib/providers/remote/firebase_provider.dart
> +  Future<List<DishTypeEntity>> getMenu() async {
use fetch

2023-08-09 15:29 UTC, ibondarovich commented on data/pubspec.lock
> +  internet_connection_checker:
remove locks

2023-08-09 15:29 UTC, ibondarovich commented on domain/lib/repositories/dishes_repository.dart
> +  Future<List<DishTypeModel>> getMenu();
fetch

2023-08-09 15:29 UTC, ibondarovich commented on domain/lib/repositories/text_scale_repository.dart
> +  double getTextScale();
same

2023-08-09 15:29 UTC, ibondarovich commented on domain/lib/usecase/dishes/fetch_dishes_usecase.dart
> +    return _dishesRepository.getMenu();
same

2023-08-09 15:29 UTC, ibondarovich commented on domain/lib/usecase/text_scale/get_text_scale_usecase.dart
> +  double execute(NoParams input) => _textScaleRepository.getTextScale();
fetch

2023-08-09 15:29 UTC, ibondarovich commented on domain/lib/usecase/text_scale/set_text_scale_usecase.dart
> +  Future<void> execute(double input) async => await _textScaleRepository.saveTextScale(input);
formatting

2023-08-09 15:29 UTC, ibondarovich commented on features/home_screen/lib/src/bloc/home_screen_bloc.dart
>        ChangeCartCountEvent event, Emitter<HomeScreenState> emit) {
,

2023-08-09 15:29 UTC, ibondarovich commented on features/home_screen/lib/src/bloc/home_screen_bloc.dart
> +      ShowMessageEvent event, Emitter<HomeScreenState> emit) {
,

2023-08-09 15:29 UTC, ibondarovich commented on features/home_screen/lib/src/bloc/home_screen_bloc.dart
> +      ChangeConnectionEvent event, Emitter<HomeScreenState> emit) {
,

2023-08-09 15:29 UTC, ibondarovich commented on features/settings/lib/src/bloc/settings/settings_bloc_bloc.dart
> +    on<OpenLinkEvent>(_openLink);
space

2023-08-09 15:29 UTC, ibondarovich commented on features/settings/lib/src/bloc/settings/settings_bloc_bloc.dart
remove space

2023-08-09 15:29 UTC, ibondarovich commented on data/lib/providers/local/hive_provider.dart
> +  Future<void> saveTextScale(double textScale) async => await _textScaleBox.put(_HiveKeys.textScaleKey, textScale);
formatting

2023-08-09 15:29 UTC, ibondarovich commented on data/lib/providers/local/hive_provider.dart
> +  double getTextScale() => _textScaleBox.get(_HiveKeys.textScaleKey) ?? AppConstants.textScales[1];
formatting

2023-08-09 15:29 UTC, ibondarovich commented on data/lib/providers/local/hive_provider.dart
>    late final Box<bool> _themeBox;
remove late?

2023-08-09 19:01 UTC, dungeon-slave commented on data/pubspec.lock
> +  internet_connection_checker:
I removed them in next PR

2023-08-09 19:02 UTC, dungeon-slave commented on features/settings/lib/src/bloc/settings/settings_bloc_bloc.dart
Enter

2023-08-09 19:04 UTC, dungeon-slave commented on data/lib/providers/local/hive_provider.dart
>    late final Box<bool> _themeBox;
I dont think that

2023-08-09 19:08 UTC, dungeon-slave commented on core_ui/lib/src/theme/app_constants.dart
> +  static const List<double> textScales = [0.8, 1.0, 1.2];
(optional)

2023-08-10 13:50 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/app_constants.dart
> +  static const List<double> textScales = [0.8, 1.0, 1.2];
enum

2023-08-10 13:52 UTC, merged